// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCSs1Uf_KX5CojhffnNqXLn-x2_VbeR-k',
    appId: '1:244163226988:web:cbf94a95950f0cea2a9749',
    messagingSenderId: '244163226988',
    projectId: 'ajar-app-2168b',
    authDomain: 'ajar-app-2168b.firebaseapp.com',
    storageBucket: 'ajar-app-2168b.firebasestorage.app',
    measurementId: 'G-NER1T4LRFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0nALHZJlK46nXjeDeGgGsz75LLoTAMCA',
    appId: '1:244163226988:android:a79058e789bb77512a9749',
    messagingSenderId: '244163226988',
    projectId: 'ajar-app-2168b',
    storageBucket: 'ajar-app-2168b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvBLKzLaI_nuywO3_8faZqppnERgfQ7Gg',
    appId: '1:244163226988:ios:4d91f3d8571fafc92a9749',
    messagingSenderId: '244163226988',
    projectId: 'ajar-app-2168b',
    storageBucket: 'ajar-app-2168b.firebasestorage.app',
    iosBundleId: 'com.example.ajarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvBLKzLaI_nuywO3_8faZqppnERgfQ7Gg',
    appId: '1:244163226988:ios:4d91f3d8571fafc92a9749',
    messagingSenderId: '244163226988',
    projectId: 'ajar-app-2168b',
    storageBucket: 'ajar-app-2168b.firebasestorage.app',
    iosBundleId: 'com.example.ajarapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCSs1Uf_KX5CojhffnNqXLn-x2_VbeR-k',
    appId: '1:244163226988:web:fe92053a20535f3b2a9749',
    messagingSenderId: '244163226988',
    projectId: 'ajar-app-2168b',
    authDomain: 'ajar-app-2168b.firebaseapp.com',
    storageBucket: 'ajar-app-2168b.firebasestorage.app',
    measurementId: 'G-GXFGM2M444',
  );
}
